### PR TITLE
Fixed the git url from git@ to https://

### PR DESCRIPTION
**Pull request by anandology**
The `git@...` url works only for people who have write access to the repo.

### CODE REVIEW

**Comment by l3gacyb3ta** [comment]
It it works for people who have a GitHub account with an ssh key, i can clone it

**Comment by l3gacyb3ta** [comment]
But yeah https is better

**Comment by anandology** [comment]
> It it works for people who have a GitHub account with an ssh key, i can clone it

Oh, I didn't know that. I assumed that ssh works only if you have write access to it. I was wrong.

**Comment by eudoxia0** [comment]
Thank you!

**Review by eudoxia0 — APPROVED** [review]

**Pull request merged**
